task 3
htmlacademy-nodejs/174891-typoteka-3 pull request #3
Opened 2021-04-06 10:38 UTC by MariaSarbaj

2021-04-12 21:32 UTC, vosyukov commented on src/service/cli/generate.js
> +    const content = JSON.stringify(generateOffers(countOffer));
Разве JSON.stringify не делается внутри writeJSONFile?

2021-09-11 13:38 UTC, dean992008 requested changes

2021-09-11 13:38 UTC, dean992008 commented on mocks.json
> +"[{\"title\":\"Ёлки. История деревьев\",\"announce\":\"Из под его пера вышло 8 платиновых альбомов. Первая большая ёлка была установлена только в 1938 году. Ёлки — это не просто красивое дерево. Это
Моки не должны попадать в git. Нужно удали их, закомитить, после чего добавить в gitignore и закомитить игнор.

2021-09-11 13:38 UTC, dean992008 commented on src/constants.js
> +module.exports.DEFAULT_COMMAND = `--help`;
Я бы рекомендовал объявлять значения как локальные а экспортировать в конце модуля все вместе.

2021-09-11 13:38 UTC, dean992008 commented on src/constants.js
> +module.exports.ExitCode = {
В перечислениях ключючи должны быть uppercase.
https://up.htmlacademy.ru/nodejs/3/criteries#b7

2021-09-11 13:38 UTC, dean992008 commented on src/service/cli/generate.js
> +const MAX_COUNT = 1000;
Значение count можно объединить в перечисление. 
https://up.htmlacademy.ru/nodejs/3/criteries#b17

2021-09-11 13:38 UTC, dean992008 commented on src/service/cli/generate.js
> +const INTERVAL_IN_MONTH = 3;
Константы должны идти перед перечислениями.

2021-09-11 13:38 UTC, dean992008 commented on src/service/cli/generate.js
> +    let countOffer = Number.parseInt(count, 10) || DEFAULT_COUNT;
Перемётные в которых не меняется значение объявляемых как const

2021-09-11 13:38 UTC, dean992008 commented on src/utils/utils.js
> +    fs.writeFileSync(fileName, content);
Писать/читать файлы синхронно, почти всегда плохо. 
здесь можешь пока не менять в следующем задании переделаем на async/await

2021-09-11 13:38 UTC, dean992008 commented on src/utils/utils.js
> +module.exports.getRandomInt = (min, max) => {
Также само объявляемых функции локально после чего экспортируем в конце модуля. 
P.S. Я такие функции обычно делаю статическими методами класса и экспортирую этот класс. Можешь сделать так, но это на твоё усмотрение.

2021-09-11 17:48 UTC, dean992008 commented
👍

2021-09-11 17:48 UTC, merged